---

- hosts:  all
  become: yes
  gather_facts: yes

  pre_tasks:

    - name: Checking for existance of k3s
      stat:
        path: "{{ k3s_install_path }}/k3s"
      register: upgrade
      tags: ['always']

    - debug:
        var:   upgrade.stat.exists
      tags: ['always']

    - import_tasks: tasks/os_prereqs.yml
      when: k3s_prereqs
      tags: ['always']

    - import_tasks: tasks/disable_swap.yml
      when: k3s_prereqs
      tags: ['always']

    - name: Update apt cache and upgrade all packages to the latest versions
      apt:
        upgrade: full
        update_cache: yes
      when: os_apt_upgrades
      tags: ['always']


  vars_files:
    - vars/packages.yml
    - vars/vars.yml

  tasks:

    - import_tasks: tasks/download_k3s.yml
      tags: ['always']

  handlers:
# Reboot , but not if k3s already exists.. don't want to reboot all the nodes in the cluster
    - name: Reboot Hosts
      reboot:
      when: not upgrade.stat.exists

- hosts:  master
  become: yes
  gather_facts: no
  vars_files:
    - vars/vars.yml

  tasks:
    - import_tasks: tasks/masters.yml

- hosts:  workers
  become: yes
  gather_facts: no
  vars_files:
    - vars/vars.yml

  tasks:
    - import_tasks: tasks/agents.yml
      tags: ['workers']

