  - name: Disabling and Removing Swap
    command: "{{ item }}"
    with_items:
      - swapoff --all
    when: ansible_swaptotal_mb > 0

  - name: Deleting swapfile
    file:
      path: /var/swap
      state: absent
