  - name: Checking if arm64
    set_fact:
      k3s_arch: -arm64
    when: ansible_facts.architecture == "aarch64"

  - name: Checking if armv7l
    set_fact:
      k3s_arch: -armf
    when: ansible_facts.architecture == "armv7l"

#  - name: Checking if amd64
#    set_fact:
#      k3s_arch: k3s
#    when: ansible_facts.architecture == "x86_64"

  - name: Abort if unsupported architecture.
    when: ansible_facts.architecture not in [ "aarch64", "armv7l", "x86_64"]
    fail: msg="{{ ansible_facts.architecture  }} is not currently supported"

