  - name: Removing unwanted packages (such as snap)
    apt:
      name: "{{ packages_to_remove }}"
      state:  absent
      purge:  true

  - name: Installing Core packages
    apt:
      name: "{{ required_packages }}"
      state: present


  - name: Enable required cgroup features.
    lineinfile:
      path: /boot/firmware/nobtcmd.txt
      backrefs: yes
      regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1)[\w=/\-\.]+)*)\s*$'
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      state: present
    register: cgroup_features
  #  when: deploy_target == 'pi'
    notify:
      - Reboot Hosts

