
  - debug:
      msg:  "k3s kubectl cordon {{ inventory_hostname }} --ignore-daemonsets=true"

  - name: "Draining/Cordoning {{ inventory_hostname }}"
    command:  "k3s kubectl drain {{ inventory_hostname }}"
    register: drain_worker
    delegate_to: master

  - debug:
      msg: "{{ drain_worker }}"

  - name: "Restarting {{ inventory_hostname }} k3s service"
    systemd:
      state: restarted
      name: k3s-agent
      daemon_reload: yes
    when: k3s_copy.changed and ( not upgrade_result.changed )

  - name: Restarting {{ inventory_hostname }}
    reboot:
    when: upgrade_result.changed

  - name: "Uncordon {{ inventory_hostname }}"
    command:  "k3s kubectl uncordon {{ inventory_hostname }}"
    register: uncordon_worker
    delegate_to: master

  - debug:
      msg: "{{ uncordon_worker }}"

  - name: "Waiting for {{ inventory_hostname }} to stabilise"
    pause:
      seconds:  120
#      prompt: "Press Enter to continue"
